### ISSUE TITLE
Range of browsers supported? Support for IE <11 ?

### ISSUE THREAD

**Issue by fabm22** [jonsamwell/angular-auto-validate#84] opened 2015-08-11 12:06 UTC
Hi,

I have no plunkr (right now) but some colleagues report me that auto-validate doesn't *seem* to work  on IE prior to version 11 .... 

It did brought to my attention that there's not seem to be any mention of level of support in browsers around in the doc. No issues neither.

Is there any known bugs with some browsers such as IE 10 ? 
Should, normally, angular-auto-validate work with IE 10 ?

Thanks for insight

**Comment by jonsamwell** [comment] 2015-08-11 12:29
Works for me on ie8-11 in multiple projects

What seems to be the issue?

**Comment by jonsamwell** [comment] 2015-08-12 00:52
Hi @fabm22

I've confirmed it works in ie8,9,10&11.  You can try for yourself here (this is an app that supports all the way down to ie8)

https://app.easilog.com

Let me know what issues you are seeing.

**Comment by fabm22** [comment] 2015-08-12 17:20
Thanks for the confirmation @jonsamwell,

My colleague was testing with IE 10, with the quirks/dev modes that the developer tools of IE comes with (ie8 / ie9 / ie10 /Edge if I'm right) and modes before Edge seemed to create errors. 

Also you DID mention IE8/older IEs in the website (http://jonsamwell.com/dynamic-angularjs-validation/, NgModelOptions Support section), sorry.

Anyway thanks for clear confirmation and if the problem seems indeed to stay, I'll setup a plunkr here.

**Comment by jonsamwell** [comment] 2015-08-13 01:33
Yeah let me know :-)

Closing for now though

**Closed by jonsamwell** 2015-08-13 01:33 UTC
Labels: question
